# Generated by Django 3.0.6 on 2020-05-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
