# Generated by Django 2.2.7 on 2020-11-28 14:40

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('algorithms', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('private_key', models.FileField(upload_to='UserUploads/Tempfile/')),
                ('date_decrypted', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'decryption',
            },
        ),
        migrations.CreateModel(
            name='UserBucketCreatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('bucketname', models.CharField(max_length=200)),
                ('accesskey', models.CharField(max_length=200)),
                ('publickey', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'userbuckets',
            },
        ),
        migrations.CreateModel(
            name='UserFileUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('bucketname', models.CharField(max_length=200)),
                ('accesskey', models.CharField(max_length=200)),
                ('secretkey', models.CharField(max_length=200)),
                ('publickey', models.CharField(max_length=200, null=True)),
                ('filename', models.CharField(max_length=200)),
                ('userfile', models.FileField(upload_to=user.models.get_upload_path)),
                ('algorithms', models.CharField(choices=[('BLOWFISH', 'BLOWFISH'), ('AES-256', 'AES-256'), ('RSA', 'RSA'), ('RSA & AES', 'RSA & AES'), ('AES & BLOWFISH', 'AES & BLOWFISH')], default='BLOWFISH', max_length=15)),
                ('filesize', models.CharField(max_length=80)),
                ('enc_time', models.CharField(max_length=80)),
                ('dec_time', models.CharField(max_length=80, null=True)),
                ('date_uploaded', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'userfiles',
            },
        ),
    ]
